# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serverlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('Cmax', models.CharField(max_length=20, verbose_name='MAC地址')),
                ('Cname', models.CharField(max_length=20, verbose_name='主机名')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('position', models.CharField(max_length=30, verbose_name='位置')),
                ('server', models.CharField(max_length=20, verbose_name='设备类型')),
                ('OS', models.CharField(max_length=20, verbose_name='操作系统')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '服务器记录列表',
            },
        ),
        migrations.CreateModel(
            name='userhostlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC地址')),
                ('hostname', models.CharField(max_length=20, verbose_name='主机名')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '员工电脑信息记录列表',
            },
        ),
    ]
