# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverlist',
            old_name='Cmax',
            new_name='Cmac',
        ),
    ]
